#!/bin/sh

# Set these paths appropriately

BIN=/Users/jose/Documents/hackriddle/HackRiddle/backend/tree-tagger-MacOSX-3.2-intel/bin
CMD=/Users/jose/Documents/hackriddle/HackRiddle/backend/tree-tagger-MacOSX-3.2-intel/cmd
LIB=/Users/jose/Documents/hackriddle/HackRiddle/backend/tree-tagger-MacOSX-3.2-intel/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/french-abbreviations-utf8
PARFILE=${LIB}/french-utf8.par

$TOKENIZER -f -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
