#!/bin/sh

# Set these paths appropriately

BIN=/Users/jose/Documents/hackriddle/HackRiddle/backend/tree-tagger-MacOSX-3.2-intel/bin
CMD=/Users/jose/Documents/hackriddle/HackRiddle/backend/tree-tagger-MacOSX-3.2-intel/cmd
LIB=/Users/jose/Documents/hackriddle/HackRiddle/backend/tree-tagger-MacOSX-3.2-intel/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovenian-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
