#!/bin/sh

# Set these paths appropriately

BIN=/Users/jose/Downloads/tree-tagger-MacOSX-3.2-intel/bin
CMD=/Users/jose/Downloads/tree-tagger-MacOSX-3.2-intel/cmd
LIB=/Users/jose/Downloads/tree-tagger-MacOSX-3.2-intel/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/romanian-abbreviations
PARFILE=${LIB}/romanian-utf8.par

$TOKENIZER -r -a $ABBR_LIST $* |
${CMD}/split-romanian.perl ${LIB}/romanian-tokens |
$TAGGER $OPTIONS $PARFILE
